from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginWithOTPForm

urlpatterns = [
    path('', views.landing, name='landing'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html', authentication_form=LoginWithOTPForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html', email_template_name='registration/password_reset_email.html', success_url='/password-reset/done/'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html', success_url='/reset/done/'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    path('profile/', views.profile_view, name='profile'),
    path('verify-email/send/', views.send_verification_email, name='send_verification_email'),
    path('verify-email/<str:token>/', views.verify_email, name='verify_email'),
    path('two-factor/setup/', views.two_factor_setup, name='two_factor_setup'),
    path('two-factor/disable/', views.disable_two_factor, name='disable_two_factor'),
    path('applications/', views.application_list, name='application_list'),
    path('applications/calendar/', views.application_calendar, name='application_calendar'),
    path('applications/kanban/', views.application_kanban, name='application_kanban'),
    path('applications/create/', views.application_create, name='application_create'),
    path('applications/<int:pk>/', views.application_detail, name='application_detail'),
    path('applications/<int:pk>/edit/', views.application_update, name='application_update'),
    path('applications/<int:pk>/delete/', views.application_delete, name='application_delete'),
    path('applications/<int:pk>/duplicate/', views.application_duplicate, name='application_duplicate'),
    path('applications/export/csv/', views.export_csv, name='export_csv'),
    path('applications/export/excel/', views.export_excel, name='export_excel'),
    path('applications/export/pdf/', views.export_pdf, name='export_pdf'),
    path('credentials/', views.credential_list, name='credential_list'),
    path('credentials/create/', views.credential_create, name='credential_create'),
    path('credentials/<int:pk>/edit/', views.credential_update, name='credential_update'),
    path('documents/', views.document_list, name='document_list'),
    path('documents/create/', views.document_create, name='document_create'),
    path('documents/<int:pk>/edit/', views.document_update, name='document_update'),
    path('templates/', views.template_list, name='template_list'),
    path('templates/create/', views.template_create, name='template_create'),
    path('templates/<int:pk>/edit/', views.template_update, name='template_update'),
    path('reminders/', views.reminder_list, name='reminder_list'),
    path('reminders/create/', views.reminder_create, name='reminder_create'),
    path('reminders/<int:pk>/edit/', views.reminder_update, name='reminder_update'),
    path('reminders/<int:pk>/toggle/', views.reminder_toggle, name='reminder_toggle'),
    path('interviews/', views.interview_list, name='interview_list'),
    path('applications/<int:pk>/checklist/add/', views.add_checklist_item, name='add_checklist_item'),
    path('applications/<int:pk>/notes/add/', views.add_interview_note, name='add_interview_note'),
    path('applications/<int:pk>/notes/<int:note_pk>/edit/', views.interview_note_edit, name='interview_note_edit'),
    path('applications/<int:pk>/notes/<int:note_pk>/delete/', views.interview_note_delete, name='interview_note_delete'),
    path('applications/<int:pk>/notes/<int:note_pk>/practice/', views.interview_practice, name='interview_practice'),
    path('applications/<int:pk>/interview-dashboard/', views.interview_dashboard, name='interview_dashboard'),
]
